const UserList = [
   {
      id: 1,
      name: "Kissiah",
      username: "Barlas",
      age: 62,
      nationality: "France",
   },
   {
      id: 2,
      name: "Bethanne",
      username: "Woodward",
      age: 55,
      nationality: "Cuba",
   },
   {
      id: 3,
      name: "Iggie",
      username: "Webberley",
      age: 85,
      nationality: "Kyrgyzstan",
   },
   {
      id: 4,
      name: "Nichole",
      username: "Ivison",
      age: 97,
      nationality: "Mongolia",
   },
   {
      id: 5,
      name: "Cecilla",
      username: "Castell",
      age: 28,
      nationality: "France",
   },
   {
      id: 6,
      name: "Saundra",
      username: "Linneman",
      age: 46,
      nationality: "Afghanistan",
   },
   {
      id: 7,
      name: "Lazarus",
      username: "Mauchlen",
      age: 17,
      nationality: "Kosovo",
   },
   {
      id: 8,
      name: "Howard",
      username: "Critchard",
      age: 27,
      nationality: "Russia",
   },
   {
      id: 9,
      name: "Perry",
      username: "Pauer",
      age: 50,
      nationality: "Indonesia",
   },
   {
      id: 10,
      name: "Phillida",
      username: "Greensitt",
      age: 80,
      nationality: "Greece",
   },
   {
      id: 11,
      name: "Toby",
      username: "Houltham",
      age: 20,
      nationality: "Philippines",
   },
   {
      id: 12,
      name: "Lara",
      username: "Waulker",
      age: 65,
      nationality: "Mongolia",
   },
   {
      id: 13,
      name: "Izzy",
      username: "Towner",
      age: 38,
      nationality: "Brazil",
   },
   {
      id: 14,
      name: "Nissa",
      username: "Oldam",
      age: 88,
      nationality: "France",
   },
   {
      id: 15,
      name: "Megan",
      username: "Greensite",
      age: 67,
      nationality: "Philippines",
   },
   {
      id: 16,
      name: "Sherlock",
      username: "Kingsley",
      age: 62,
      nationality: "Brazil",
   },
   {
      id: 17,
      name: "Lina",
      username: "MacAndie",
      age: 71,
      nationality: "Switzerland",
   },
   {
      id: 18,
      name: "Mandi",
      username: "Halversen",
      age: 93,
      nationality: "South Korea",
   },
   {
      id: 19,
      name: "Clywd",
      username: "Girkin",
      age: 66,
      nationality: "United States",
   },
   {
      id: 20,
      name: "Donal",
      username: "Tracey",
      age: 94,
      nationality: "Greece",
   },
];

module.exports = { UserList };
